Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/lac/PIRadar2019/src/test_1estacion.py", line 25, in <module>
    model = load_model(model_dir)
  File "/home/lac/miniconda2/envs/lac/lib/python3.7/site-packages/keras/engine/saving.py", line 417, in load_model
    f = h5dict(filepath, 'r')
  File "/home/lac/miniconda2/envs/lac/lib/python3.7/site-packages/keras/utils/io_utils.py", line 186, in __init__
    self.data = h5py.File(path, mode=mode)
  File "/home/lac/miniconda2/envs/lac/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/home/lac/miniconda2/envs/lac/lib/python3.7/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/home/lac/modelos/CerroObero/modeloVgg1.3Smote.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
